version: '3.5'
services:

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent_app
    env_file: .env
    volumes:
      - /apps/qbitorrent/config:/config
      - /apps/qbitorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always