version: "3.5"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent_app
    env_file: .env
    volumes:
      - /apps/qbitorrent:/config
      - /apps/qbitorrent:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always