version: "3.5"

services:
  db:
    image: postgres:11-alpine
    container_name: wiki_db
    env_file: .env
    logging:
      driver: "none"
    restart: always
    volumes:
      - /apps/wiki/db-data:/var/lib/postgresql/data

  app:
    image: requarks/wiki:latest
    container_name: wiki_app
    depends_on:
      - db
    env_file: .env
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /apps/wiki/app-data:/wiki/data/content