version: '3.5'
services:

  portainer:
    image: selfhostedpro/yacht:latest
    container_name: yacht_app
    volumes:
      - /apps/yacht/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - 8000:8000