version: '3.5'
services:

   db:
     image: mysql:5.7
     container_name: wordpress_db
     volumes:
       - /apps/wordpress/db:/var/lib/mysql
     restart: always
     env_file: .env

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wordpress_app
     volumes:
       - /apps/wordpress/apps:/var/www/html
       - /apps/wordpress/php:/usr/local/etc/php
       - /apps/wordpress/logs:/var/log/apache2
     ports:
       - 80:80
     restart: always
     env_file: .env