version: '3.5'
services:

   db:
     image: mysql:5.7
     container_name: wordpress_db
     volumes:
       - /apps/wordpress/laurene/db:/var/lib/mysql
     restart: always
     env_file: .env

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wordpress_app
     volumes:
       - /apps/wordpress/laurene/apps:/var/www/html
     ports:
       - "80:80"
     restart: always
     env_file: .env