version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    volumes:
      - /apps/jellyfin/config:/config
      - /apps/jellyfin/cache:/cache
      - /apps/jellyfin/media:/media
      - /srv/dev-disk-by-uuid-1513a24c-5462-4f1b-9712-7fb1ae5d8a2e/Samaf/files/Videos/Théatre:/media/Théatre
      - /srv/dev-disk-by-uuid-1513a24c-5462-4f1b-9712-7fb1ae5d8a2e/Samaf/files/Videos/Spectacle:/media/Spectacle
      - /srv/dev-disk-by-uuid-1513a24c-5462-4f1b-9712-7fb1ae5d8a2e/Samaf/files/Videos/Manga:/media/Manga
      - /srv/dev-disk-by-uuid-1513a24c-5462-4f1b-9712-7fb1ae5d8a2e/Samaf/files/Videos/Disney:/media/Disney
      - /srv/dev-disk-by-uuid-1513a24c-5462-4f1b-9712-7fb1ae5d8a2e/Samaf/files/Videos/Séries:/media/Séries
      - /srv/dev-disk-by-uuid-1513a24c-5462-4f1b-9712-7fb1ae5d8a2e/Samaf/files/Videos/Emission:/media/Emission
      - /srv/dev-disk-by-uuid-1513a24c-5462-4f1b-9712-7fb1ae5d8a2e/Samaf/files/Videos/Films:/media/Films
      - /srv/dev-disk-by-uuid-1513a24c-5462-4f1b-9712-7fb1ae5d8a2e/Samaf/files/Videos/Tutoriels:/media/Tutoriels
    restart: "always"
    ports:
      - "8096:8096"
      - "7359:7359"
      - "1900:1900"