version: '3.5'
services:

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin_app
    volumes:
      - /apps/jellyfin/config:/config
      - /apps/jellyfin/cache:/cache
      - /apps/jellyfin/media:/media
      - /apps/jellyfin/media/Théatre:/media/Théatre
      - /apps/jellyfin/media/Spectacle:/media/Spectacle
      - /apps/jellyfin/media/Manga:/media/Manga
      - /apps/jellyfin/media/Disney:/media/Disney
      - /apps/jellyfin/media/Séries:/media/Séries
      - /apps/jellyfin/media/Emission:/media/Emission
      - /apps/jellyfin/media/Films:/media/Films
      - /apps/jellyfin/media/Tutoriels:/media/Tutoriels
    restart: always
    ports:
      - 8096:8096
      - 7359:7359
      - 1900:1900