version: '3.5'
services:

  pufferpanel:
    image: pufferpanel/pufferpanel:latest
    container_name: pufferpanel_app
    volumes:
      - /apps/pufferpanel/config:/etc/pufferpanel
      - /apps/pufferpanel/servers:/var/lib/pufferpanel/servers
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - 8080:8080
      - 27015:27015 # Port
      - 27016:27016 # Client Port
      - 27017:27017 # GOTV
      - 5657:5657