version: '3.5'
services:

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: kuma_app
    volumes:
      - /apps/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - 3001:3001