version: '3.5'
services:

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm_app
    ports:
      - '80:80' # ne pas modifier
      - '81:81'
      - '443:443' # ne pas modifier
    restart: always
    env_file: .env
    volumes:
      - /apps/npm/data:/data
      - /apps/npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
      
  db:
    image: jc21/mariadb-aria:latest
    container_name: npm_db
    restart: always
    env_file: .env
    volumes:
      - /apps/npm/mysql:/var/lib/mysql